#!/bin/sh
# Rebuild src/testing/reference-schema.ts and reference-ddl.ts from createIdentity(), the way a
# product generates its own tables:
#   1. `auth generate`  (Better Auth CLI, Drizzle target) -> raw schema
#   2. house adjustments: tables in the `identity` pg schema, native `uuid` ids (ids are uuidv7
#      strings), `timestamptz` instead of `timestamp` (WP-9 D7)
#   3. `drizzle-kit generate` -> SQL, embedded as REFERENCE_DDL
set -eu
cd "$(dirname "$0")/.."
RAW="$(mktemp)"
OUT="$(mktemp -d)"
BETTER_AUTH_TELEMETRY=0 pnpm exec auth generate --config scripts/auth-cli-config.ts --output "$RAW" -y >/dev/null 2>&1
python3 - "$RAW" <<'PY'
import re, sys
s = open(sys.argv[1]).read()
m = re.search(r'import \{([^}]*)\} from "drizzle-orm/pg-core";', s)
names = [n.strip() for n in m.group(1).split(',') if n.strip() and n.strip() != 'pgTable']
names = sorted(set(names + ['pgSchema', 'uuid']))
s = s.replace(m.group(0), 'import { ' + ', '.join(names) + ' } from "drizzle-orm/pg-core";\n\n'
  '/** Each product owns the auth tables in its own `identity` schema (identity plan §7). */\n'
  'export const identity = pgSchema("identity");')
s = s.replace('pgTable(', 'identity.table(')
s = re.sub(r'text\("(id|user_id|organization_id|active_organization_id|impersonated_by|inviter_id)"\)', r'uuid("\1")', s)
s = re.sub(r'timestamp\("([a-z_]+)"\)', r'timestamp("\1", { withTimezone: true })', s)
header = ('// GENERATED by scripts/regenerate-reference-schema.sh from `auth generate`, then adjusted:\n'
          '// `identity` pg schema, native uuid ids, timestamptz. Do not edit by hand.\n'
          '')
open('src/testing/reference-schema.ts', 'w').write(header + s)
PY
cat > "$OUT/drizzle.config.ts" <<CFG
export default { dialect: 'postgresql', schema: '$PWD/src/testing/reference-schema.ts', out: '$OUT/migrations', schemaFilter: ['identity'] };
CFG
pnpm exec drizzle-kit generate --config "$OUT/drizzle.config.ts" --name reference >/dev/null
python3 - "$OUT" <<'PY'
import glob, sys
sql = open(glob.glob(sys.argv[1] + '/migrations/*.sql')[0]).read().replace('`', '\\`').replace('${', '\\${')
open('src/testing/reference-ddl.ts', 'w').write(
  '// GENERATED by scripts/regenerate-reference-schema.sh. Do not edit by hand.\n'
  '/** The SQL for `reference-schema.ts`, statements separated by `--> statement-breakpoint`. */\n'
  'export const REFERENCE_DDL = `' + sql + '`;\n')
PY
pnpm exec prettier --write src/testing/reference-schema.ts src/testing/reference-ddl.ts >/dev/null
rm -rf "$OUT" "$RAW"
echo "reference schema + DDL regenerated"
