#!/bin/sh
# Rebuild src/db/schema.ts and drizzle/ from the identity options, the way a product would:
#   1. `auth generate`  (Better Auth CLI, Drizzle target) -> raw schema
#   2. house adjustments: `identity` pg schema, native uuid columns (ids are uuidv7 strings)
#   3. `drizzle-kit generate` -> drizzle/0000_auth_tables.sql
set -eu
cd "$(dirname "$0")/.."
RAW="$(mktemp)"
BETTER_AUTH_TELEMETRY=0 node_modules/.bin/auth generate --config scripts/auth-cli-config.ts --output "$RAW" -y >/dev/null
python3 - "$RAW" <<'PY'
import re, sys
s = open(sys.argv[1]).read()
s = s.replace('import { pgTable, text, timestamp, boolean, index } from "drizzle-orm/pg-core";',
  'import { pgSchema, text, timestamp, boolean, index, uuid } from "drizzle-orm/pg-core";\n\n'
  '/** Each product owns the auth tables in its own `identity` schema (identity plan §7). */\n'
  'export const identity = pgSchema("identity");')
s = s.replace('pgTable(', 'identity.table(')
s = re.sub(r'text\("(id|user_id|organization_id|active_organization_id|impersonated_by|inviter_id)"\)', r'uuid("\1")', s)
header = ('// GENERATED by scripts/regenerate-schema.sh from `auth generate` (Better Auth CLI, Drizzle target),\n'
          '// then adjusted: tables in the `identity` schema, id columns as native `uuid`.\n'
          '// Do not edit by hand; change createIdentity() and regenerate.\n')
open('src/db/schema.ts', 'w').write(header + s)
PY
rm -rf drizzle
pnpm exec drizzle-kit generate --name auth_tables >/dev/null
echo "schema.ts + drizzle/0000_auth_tables.sql regenerated"
